data:
  source: "sklearn"           # ‚Üê NUEVO
  name: "diabetes"            # o iris, wine, breast_cancer
  target: "target"

model:
  type: "RandomForestClassifier"
  params:
    n_estimators: 150
    max_depth: 6

training:
  test_size: 0.2
  random_state: 42

mlflow:
  experiment_name: "/Users/alexanderdiaz21795@gmail.com/mlops-demo-experiment"
  registered_model_name: "demo_regressor"

output:
  model_path: "models/model.pkl"
