name: Multi Job Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build simulado
        run: echo "Compilando..."

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Ejecutar tests
        run: echo "Pruebas completadas"

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Deploy simulado
        run: echo "Deploy a ambiente DEV"
