name: Variables Demo

on:
  workflow_dispatch:

env:
  GREETING: "Hola Kevin"
  ENVIRONMENT: "dev"

jobs:
  show-vars:
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar variables
        run: |
          echo "GREETING: ${{ env.GREETING }}"
          echo "ENVIRONMENT: ${{ env.ENVIRONMENT }}"
          echo "Runner OS: ${{ runner.os }}"
